#!/usr/bin/env python

#-------------- Import ------------------#
import numpy as np
import pandas as pd
import sklearn 
import matplotlib.pyplot as plt


#-------------- Pulling the data from pickle file -----------#
nutrition = pd.read_pickle("./nutrition_data_clean.pkl")


#-------------- Cleaning dataset --------------------#
nutrition = nutrition.dropna()
print(nutrition)

#-------------- Extracting the nutrition data as the features, labelled X ------------#
X = nutrition.iloc[:,10:]
print(X)

#-------------- Extracting the GHGE ------------------------------------#
y = nutrition.iloc[:,6:7]
print(y)

#-------------- Test train splitting ------------------------#
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
# size is the size of the test dataset. size=0.2 means 80:20 test:train split

